# Generated by Django 2.2.6 on 2019-10-27 04:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('file_name', models.CharField(max_length=120)),
                ('file_type', models.CharField(blank=True, max_length=50, null=True)),
                ('file_url', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
